const ROLE_HARVESTER: ROLE_HARVESTER = "harvester";
const ROLE_BUILDER: ROLE_BUILDER = "builder";
const ROLE_UPGRADER: ROLE_UPGRADER = "upgrader";
const ROLE_MAINTANANCE: ROLE_MAINTANANCE = "maintenance";
const ROLE_TRANSFERER: ROLE_TRANSFERER = "transferer";
const ROLE_SPAWN_TRANSFERER: ROLE_SPAWN_TRANSFERER = "spawn_transferer";
const ROLE_WITHDRAWER: ROLE_WITHDRAWER = "withdrawer";

export {
  ROLE_HARVESTER,
  ROLE_BUILDER,
  ROLE_UPGRADER,
  ROLE_MAINTANANCE,
  ROLE_TRANSFERER,
  ROLE_SPAWN_TRANSFERER,
  ROLE_WITHDRAWER
};
